import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Main content */}
        <main className="flex-1">{children}</main>

        {/* Footer */}
        <footer className="bg-gradient-to-r from-blue-600 to-purple-600 text-white py-6 mt-10">
          <div className="container mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
            {/* Logo / Title */}
            <span className="text-lg font-semibold tracking-wide">
              Simple Blog
            </span>

            {/* Links */}
            <ul className="flex gap-6 text-sm">
              <li>
                <a
                  href="#"
                  className="hover:text-gray-200 transition-colors"
                >
                  Privacy Policy
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="hover:text-gray-200 transition-colors"
                >
                  Terms of Service
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="hover:text-gray-200 transition-colors"
                >
                  Contact
                </a>
              </li>
            </ul>

            {/* Copyright */}
            <p className="text-xs text-gray-200">
                    Made with ❤️ by{" "}
      <a
        href="https://github.com/dboatengg"
        target="_blank"
        rel="noopener noreferrer"
        className="font-semibold text-white hover:underline"
      >
        Dickson
      </a>{" "}
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
